name: cloudmonkey
version: git
summary: Apache CloudStack CLI
description: |
  An CLI and interactive shell that simplifies configuration and management of
  Apache CloudStack, the opensource IAAS cloud computing platform.
license: Apache-2.0
grade: stable
confinement: strict

apps:
  cloudmonkey:
    command: bin/cmk
    plugs:
    - home
    - network

parts:
  go:
    source-tag: go1.12.1
  cloudmonkey:
    after: [go]
    source: https://github.com/apache/cloudstack-cloudmonkey
    source-type: git
    source-tag: 6.0.0
    plugin: go
    go-importpath: github.com/apache/cloudstack-cloudmonkey
    build-packages:
      - gcc
      - make
      - file
    override-build: |
      set -eu
      go version
      GIT_SHA=$(git rev-parse --short HEAD)
      DATE=$(date +%FT%T%z)
      go build -mod=vendor -ldflags='-s -w -X main.GitSHA=$(GIT_SHA) -X main.BuildDate=$(DATE)' -o cmk cmk.go
      file cmk
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mv cmk $SNAPCRAFT_PART_INSTALL/bin/
      strip --remove-section=.comment --remove-section=.note $SNAPCRAFT_PART_INSTALL/bin/cmk
